kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: ubuntu
  commands:
  - apt-get update
  - curl https://raw.githubusercontent.com/WolfOSP/scripts/hmp/changelog-generator.sh -o changelog-generator.sh
  - bash changelog-generator.sh
  - echo "heo"
  - pwd
  - echo $DRONE_WORKSPACE
  - cd $HOME
  - pwd
  - cd $DRONE_WORKSPACE
